version: '3.8'

services:
  neo4j:
    image: neo4j:5
    container_name: vern-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/password"
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: vern_backend/Dockerfile
    container_name: vern-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - neo4j
    restart: unless-stopped

  frontend:
    build:
      context: ./vern_frontend
      dockerfile: Dockerfile
    container_name: vern-frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

# Optional: Add volumes for persistent data if needed
#   volumes:
#     - ./db:/db
#     - ./chroma_data:/chroma_data
