services:
  neo4j:
    image: neo4j:5
    container_name: vern-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/password"
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: vern_backend/Dockerfile
    container_name: vern-backend
    environment:
      - SQLITE_DB_PATH=/app/data/vern.sqlite
      - CHROMA_DB_PATH=/app/data/chroma
    volumes:
      - ./data:/app/data
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - neo4j
    restart: unless-stopped

  frontend:
    build:
      context: ./vern_frontend
      dockerfile: Dockerfile
    container_name: vern-frontend
    ports:
      - "3000:3000"
    # volumes:
    #   - ./vern_frontend:/app
    depends_on:
      - backend
    restart: unless-stopped

# Optional: Add volumes for persistent data if needed
#   volumes:
#     - ./db:/db
#     - ./chroma_data:/chroma_data
