# Agent backend/model configuration for VERN
# Specify which backend/model/API each agent should use.
# Format for Ollama: "ollama-<model>"
# Example: "ollama-qwen3:0.6b", "ollama-phi", "fake_llm", "qwen3-0.6b" (transformers)

dev_team: ollama-qwen3:0.6b
knowledge_broker: ollama-qwen3:0.6b
research: ollama-qwen3:0.6b
admin: none
# Add more agents as needed...
